before:
  hooks:
    - go mod tidy

builds:
  - id: fcp
    main: ./cmd/fcp/main.go
    binary: fcp
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -s -w -X main.FCP_VERSION={{.Version}}

  - id: fcp-inspect
    main: ./cmd/fcp-inspect/main.go
    binary: fcp-inspect
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -s -w -X main.FCP_VERSION={{.Version}}

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

brews:
  - commit_author:
      name: Panagiotis Vryonis
      email: vrypan@gmail.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    directory: Formula
    caveats: |
      Both binaries have been installed:
        - fcp → `fcp --help`
        - fcp-inspect → `fcp-inspect --help`
    homepage: "https://github.com/vrypan/fcp"
    description: "Copy data from/to farcaster and the local filesystem"
    license: "MIT"
    skip_upload: auto
    install: |
      bin.install "fcp"
      bin.install "fcp-inspect"
    test: |
      system "#{bin}/fcp --version"
      system "#{bin}/fcp-inspect --version"
    repository:
      owner: vrypan
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
