// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: admin_rpc.proto

package farcaster

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_admin_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_admin_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_admin_rpc_proto_rawDescGZIP(), []int{0}
}

type RetryBlockNumberRange struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	StartBlockNumber uint64                 `protobuf:"varint,1,opt,name=start_block_number,json=startBlockNumber,proto3" json:"start_block_number,omitempty"`
	StopBlockNumber  uint64                 `protobuf:"varint,2,opt,name=stop_block_number,json=stopBlockNumber,proto3" json:"stop_block_number,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RetryBlockNumberRange) Reset() {
	*x = RetryBlockNumberRange{}
	mi := &file_admin_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryBlockNumberRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryBlockNumberRange) ProtoMessage() {}

func (x *RetryBlockNumberRange) ProtoReflect() protoreflect.Message {
	mi := &file_admin_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryBlockNumberRange.ProtoReflect.Descriptor instead.
func (*RetryBlockNumberRange) Descriptor() ([]byte, []int) {
	return file_admin_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *RetryBlockNumberRange) GetStartBlockNumber() uint64 {
	if x != nil {
		return x.StartBlockNumber
	}
	return 0
}

func (x *RetryBlockNumberRange) GetStopBlockNumber() uint64 {
	if x != nil {
		return x.StopBlockNumber
	}
	return 0
}

type RetryOnchainEventsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*RetryOnchainEventsRequest_Fid
	//	*RetryOnchainEventsRequest_BlockRange
	Kind          isRetryOnchainEventsRequest_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryOnchainEventsRequest) Reset() {
	*x = RetryOnchainEventsRequest{}
	mi := &file_admin_rpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryOnchainEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryOnchainEventsRequest) ProtoMessage() {}

func (x *RetryOnchainEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_rpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryOnchainEventsRequest.ProtoReflect.Descriptor instead.
func (*RetryOnchainEventsRequest) Descriptor() ([]byte, []int) {
	return file_admin_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *RetryOnchainEventsRequest) GetKind() isRetryOnchainEventsRequest_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *RetryOnchainEventsRequest) GetFid() uint64 {
	if x != nil {
		if x, ok := x.Kind.(*RetryOnchainEventsRequest_Fid); ok {
			return x.Fid
		}
	}
	return 0
}

func (x *RetryOnchainEventsRequest) GetBlockRange() *RetryBlockNumberRange {
	if x != nil {
		if x, ok := x.Kind.(*RetryOnchainEventsRequest_BlockRange); ok {
			return x.BlockRange
		}
	}
	return nil
}

type isRetryOnchainEventsRequest_Kind interface {
	isRetryOnchainEventsRequest_Kind()
}

type RetryOnchainEventsRequest_Fid struct {
	Fid uint64 `protobuf:"varint,1,opt,name=fid,proto3,oneof"`
}

type RetryOnchainEventsRequest_BlockRange struct {
	BlockRange *RetryBlockNumberRange `protobuf:"bytes,2,opt,name=block_range,json=blockRange,proto3,oneof"`
}

func (*RetryOnchainEventsRequest_Fid) isRetryOnchainEventsRequest_Kind() {}

func (*RetryOnchainEventsRequest_BlockRange) isRetryOnchainEventsRequest_Kind() {}

var File_admin_rpc_proto protoreflect.FileDescriptor

var file_admin_rpc_proto_rawDesc = string([]byte{
	0x0a, 0x0f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x13, 0x6f, 0x6e, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x14, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65,
	0x5f, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x07, 0x0a, 0x05,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x71, 0x0a, 0x15, 0x52, 0x65, 0x74, 0x72, 0x79, 0x42, 0x6c,
	0x6f, 0x63, 0x6b, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x2c,
	0x0a, 0x12, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x6e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x10, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x2a, 0x0a, 0x11,
	0x73, 0x74, 0x6f, 0x70, 0x5f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0f, 0x73, 0x74, 0x6f, 0x70, 0x42, 0x6c, 0x6f,
	0x63, 0x6b, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x72, 0x0a, 0x19, 0x52, 0x65, 0x74, 0x72,
	0x79, 0x4f, 0x6e, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x03, 0x66, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x48, 0x00, 0x52, 0x03, 0x66, 0x69, 0x64, 0x12, 0x39, 0x0a, 0x0b, 0x62, 0x6c, 0x6f,
	0x63, 0x6b, 0x5f, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16,
	0x2e, 0x52, 0x65, 0x74, 0x72, 0x79, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x4e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x48, 0x00, 0x52, 0x0a, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x52,
	0x61, 0x6e, 0x67, 0x65, 0x42, 0x06, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x32, 0x6a, 0x0a, 0x0c,
	0x41, 0x64, 0x6d, 0x69, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x20, 0x0a, 0x0e,
	0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x12, 0x06,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x06, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x38,
	0x0a, 0x12, 0x52, 0x65, 0x74, 0x72, 0x79, 0x4f, 0x6e, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x73, 0x12, 0x1a, 0x2e, 0x52, 0x65, 0x74, 0x72, 0x79, 0x4f, 0x6e, 0x63, 0x68,
	0x61, 0x69, 0x6e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x06, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_admin_rpc_proto_rawDescOnce sync.Once
	file_admin_rpc_proto_rawDescData []byte
)

func file_admin_rpc_proto_rawDescGZIP() []byte {
	file_admin_rpc_proto_rawDescOnce.Do(func() {
		file_admin_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admin_rpc_proto_rawDesc), len(file_admin_rpc_proto_rawDesc)))
	})
	return file_admin_rpc_proto_rawDescData
}

var file_admin_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_admin_rpc_proto_goTypes = []any{
	(*Empty)(nil),                     // 0: Empty
	(*RetryBlockNumberRange)(nil),     // 1: RetryBlockNumberRange
	(*RetryOnchainEventsRequest)(nil), // 2: RetryOnchainEventsRequest
}
var file_admin_rpc_proto_depIdxs = []int32{
	1, // 0: RetryOnchainEventsRequest.block_range:type_name -> RetryBlockNumberRange
	0, // 1: AdminService.UploadSnapshot:input_type -> Empty
	2, // 2: AdminService.RetryOnchainEvents:input_type -> RetryOnchainEventsRequest
	0, // 3: AdminService.UploadSnapshot:output_type -> Empty
	0, // 4: AdminService.RetryOnchainEvents:output_type -> Empty
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_admin_rpc_proto_init() }
func file_admin_rpc_proto_init() {
	if File_admin_rpc_proto != nil {
		return
	}
	file_onchain_event_proto_init()
	file_username_proof_proto_init()
	file_admin_rpc_proto_msgTypes[2].OneofWrappers = []any{
		(*RetryOnchainEventsRequest_Fid)(nil),
		(*RetryOnchainEventsRequest_BlockRange)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admin_rpc_proto_rawDesc), len(file_admin_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_admin_rpc_proto_goTypes,
		DependencyIndexes: file_admin_rpc_proto_depIdxs,
		MessageInfos:      file_admin_rpc_proto_msgTypes,
	}.Build()
	File_admin_rpc_proto = out.File
	file_admin_rpc_proto_goTypes = nil
	file_admin_rpc_proto_depIdxs = nil
}
