// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: node_state.proto

package farcaster

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OnChainEventState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LastL2Block   uint64                 `protobuf:"varint,3,opt,name=last_l2_block,json=lastL2Block,proto3" json:"last_l2_block,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnChainEventState) Reset() {
	*x = OnChainEventState{}
	mi := &file_node_state_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnChainEventState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnChainEventState) ProtoMessage() {}

func (x *OnChainEventState) ProtoReflect() protoreflect.Message {
	mi := &file_node_state_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnChainEventState.ProtoReflect.Descriptor instead.
func (*OnChainEventState) Descriptor() ([]byte, []int) {
	return file_node_state_proto_rawDescGZIP(), []int{0}
}

func (x *OnChainEventState) GetLastL2Block() uint64 {
	if x != nil {
		return x.LastL2Block
	}
	return 0
}

type FnameState struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	LastFnameProof uint64                 `protobuf:"varint,3,opt,name=last_fname_proof,json=lastFnameProof,proto3" json:"last_fname_proof,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FnameState) Reset() {
	*x = FnameState{}
	mi := &file_node_state_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FnameState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FnameState) ProtoMessage() {}

func (x *FnameState) ProtoReflect() protoreflect.Message {
	mi := &file_node_state_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FnameState.ProtoReflect.Descriptor instead.
func (*FnameState) Descriptor() ([]byte, []int) {
	return file_node_state_proto_rawDescGZIP(), []int{1}
}

func (x *FnameState) GetLastFnameProof() uint64 {
	if x != nil {
		return x.LastFnameProof
	}
	return 0
}

var File_node_state_proto protoreflect.FileDescriptor

var file_node_state_proto_rawDesc = string([]byte{
	0x0a, 0x10, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x37, 0x0a, 0x11, 0x4f, 0x6e, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x22, 0x0a, 0x0d, 0x6c, 0x61, 0x73, 0x74, 0x5f,
	0x6c, 0x32, 0x5f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b,
	0x6c, 0x61, 0x73, 0x74, 0x4c, 0x32, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x22, 0x36, 0x0a, 0x0a, 0x46,
	0x6e, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x28, 0x0a, 0x10, 0x6c, 0x61, 0x73,
	0x74, 0x5f, 0x66, 0x6e, 0x61, 0x6d, 0x65, 0x5f, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x0e, 0x6c, 0x61, 0x73, 0x74, 0x46, 0x6e, 0x61, 0x6d, 0x65, 0x50, 0x72,
	0x6f, 0x6f, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_node_state_proto_rawDescOnce sync.Once
	file_node_state_proto_rawDescData []byte
)

func file_node_state_proto_rawDescGZIP() []byte {
	file_node_state_proto_rawDescOnce.Do(func() {
		file_node_state_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_node_state_proto_rawDesc), len(file_node_state_proto_rawDesc)))
	})
	return file_node_state_proto_rawDescData
}

var file_node_state_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_node_state_proto_goTypes = []any{
	(*OnChainEventState)(nil), // 0: OnChainEventState
	(*FnameState)(nil),        // 1: FnameState
}
var file_node_state_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_node_state_proto_init() }
func file_node_state_proto_init() {
	if File_node_state_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_node_state_proto_rawDesc), len(file_node_state_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_node_state_proto_goTypes,
		DependencyIndexes: file_node_state_proto_depIdxs,
		MessageInfos:      file_node_state_proto_msgTypes,
	}.Build()
	File_node_state_proto = out.File
	file_node_state_proto_goTypes = nil
	file_node_state_proto_depIdxs = nil
}
